#!/bin/bash

source util

step "Switching to $master branch"
git checkout $master || exit 1

step "Pulling latest changes from $master origin"
git pull || exit 1

step "Update submodules"
git submodule update --init --recursive || exit 1

step "Getting back to development branch"
git checkout $branch || exit 1

step "Rebasing your branch on $master"
git rebase $master || exit 1