#!/bin/bash

export branch=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

case "$branch" in
    "master")
        echo -e '\033[1;31mYou should *NEVER* push from \033[1;32mmaster\033[1;31m branch!\033[m'
        echo -e ''
        echo -e 'To resolve problem do the following steps:'
        echo -e '  1. Move all you commits from \033[1;32mmaster\033[m to your development branch.'
        echo -e '     \033[0;33mUse git-cherry-pick command.\033[m'
        echo -e '  2. Remove all you commits from \033[1;32mmaster\033[m.'
        echo -e '\033[0;33m     Use git-reset command.\033[m'
        echo -e '  3. Select development branch and make push again.'
        echo -e ''
        echo -e '\033[1;31mConsult your PM if you have problems with it.\033[m'
        ;;
    "")
        echo -e '\033[1;31mMove to git repository before push\033[m'
        ;;
    *)
        echo && \
        echo -e '\033[0;36mSwitching to master branch' && \
        echo -e '============================\033[m' && \
        git checkout master && \
        \
        echo && \
        echo -e '\033[0;36mPulling latest changes from master origin' && \
        echo -e '============================\033[m' && \
        git pull && \
        \
        echo && \
        echo -e '\033[0;36mGetting back to private branch' && \
        echo -e '============================\033[m' && \
        git checkout $branch && \
        \
        echo && \
        echo -e '\033[0;36mRebasing your branch on master' && \
        echo -e '============================\033[m' && \
        git rebase master && \
        \
        echo && \
        echo -e '\033[0;36mReturning to master branch' && \
        echo -e '============================\033[m' && \
        git checkout master && \
        \
        echo && \
        echo -e '\033[0;36mMerging your changes with master' && \
        echo -e '============================\033[m' && \
        git merge $branch && \
        echo && \
        echo -e '\033[0;36mPushing your changes from master to origin' && \
        echo -e '============================\033[m' && \
        git push && \
        \
        echo && \
        echo -e '\033[0;36mGetting back to private branch' && \
        echo -e '============================\033[m' && \
        git checkout $branch && \
        echo
        ;;
esac
